export const COLORS = {
  PRIMARY_BACKGROUND: "#cae1f1",
  SECONDARY_BACKGROUND: "#f1f1f1",
  PRIMARY_TEXT: "#000000",
  SUBTITLE_TEXT: "#666",
  PRIMARY_ACTIVE_BUTTON: "#2563eb",
  BUTTON_TEXT: "#fff",
  PRIMARY_RED: "#c83135",
  SUCCESS: "#4CAF50",
  PRIMARY_BORDER: "#1b7aed",
  PLACEHOLDER: "#a0a0a0",
  SELECTED_BACKGROUND: "#bfdbfe",
};
